### ISSUE TITLE
How to build the AM4

### ISSUE THREAD

**Issue by ynueriap** [NOAA-GFDL/AM4#43]
Dear all,
I tried to compile the AM4 model with the intel ifort, mpiifort based on the configuration of the intel.mk template. 
I encountered an error in the file AM4/src/FMS/mpp/include/mpp_type_mpi.h, which is related to the definition of the rank 
The error message is as follows:
make[1]: warning:  Clock skew detected.  Your build may be incomplete.
make[1]: Leaving directory `/disk01/liuy/models/AM4/exec/coupler'
mpiifort coupler/libcoupler.a atmos_dyn/libatmos_dyn.a ice_sis/libice_sis.a atmos_cubed_sphere/libatmos_cubed_sphere.a atmos_phys/libatmos_phys.a mom6/libmom6.a land_lad2/libland_lad2.a fms/libfms.a    -L/disk01/liuy/apps/netcdf/lib -lnetcdf -lnetcdff  -L/opt/intel/impi/5.0.2.044/intel64/lib -lmpi -L/disk01/liuy/apps/hdf5/lib -lhdf5 -lhdf5_fortran -lhdf5_hl -lhdf5hl_fortran  -L/opt/intel/mkl/lib/intel64  -lmkl_blas95_lp64 -lmkl_lapack95_lp64 -lmkl_intel_lp64 -lmkl_core -lmkl_sequential -o am4_xanadu_2021.02.x
ld: warning: libimf.so, needed by /disk01/liuy/apps/netcdf/lib/libnetcdf.so, not found (try using -rpath or -rpath-link)
ld: warning: libsvml.so, needed by /disk01/liuy/apps/netcdf/lib/libnetcdf.so, not found (try using -rpath or -rpath-link)
ld: warning: libirng.so, needed by /disk01/liuy/apps/netcdf/lib/libnetcdf.so, not found (try using -rpath or -rpath-link)
ld: warning: libintlc.so.5, needed by /disk01/liuy/apps/netcdf/lib/libnetcdf.so, not found (try using -rpath or -rpath-link)
ld: warning: libifport.so.5, needed by /disk01/liuy/apps/netcdf/lib/libnetcdff.so, not found (try using -rpath or -rpath-link)
fms/libfms.a(mpp.o): In function `mpp_type_create_int4':
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h:46: undefined reference to `rank_'
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h:60: undefined reference to `rank_'
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h:75: undefined reference to `rank_'
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h:76: undefined reference to `rank_'
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h:77: undefined reference to `rank_'
fms/libfms.a(mpp.o):/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h:81: more undefined references to `rank_' follow
ld: am4_xanadu_2021.02.x: hidden symbol `__intel_cpu_features_init_x' in /opt/intel/composer_xe_2015.1.133/compiler/lib/intel64/libirc.a(cpu_feature_disp.o) is referenced by DSO
ld: final link failed: Nonrepresentable section on output
make: *** [am4_xanadu_2021.02.x] Error 1

How do can fix this issue.
Thanks so much

**Comment by thomas-robinson** [comment]
@ynueriap this looks like you have a netcdf and/or an MPI issue on your system.  Are you able to build other applications that require linking in netcdf and mpi?  You may need to link in more libraries if they aren't included in your netcdf and MPI already. 

If you have access to singularity or docker, there are dockerfiles and singularity def files included with the latest release and version on the main branch.

**Comment by ynueriap** [comment]
@thomas-robinson Thank you so much for your reply. 
At first, I have no access to singularity and docker, so I could not get the latest def files.
Secondly, the build errors I mentioned above appear in the file AM4/src/FMS/mpp/include/mpp_type_mpi.h. 
If I build the AM4 mode based on he original mpp_type_mpi.h. file which has no definition on the the rank function, I encounter the following errors:
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(45): error #6404: This name does not have a type, and must have an explicit type.   [RANK]
        if (dtype%ndims /= rank(field)) cycle
---------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(74): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%sizes(rank(field)))
-------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(75): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%subsizes(rank(field)))
----------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(76): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%starts(rank(field)))
--------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(45): error #6404: This name does not have a type, and must have an explicit type.   [RANK]
        if (dtype%ndims /= rank(field)) cycle
---------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(74): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%sizes(rank(field)))
-------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(75): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%subsizes(rank(field)))
----------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(76): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%starts(rank(field)))
--------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(45): error #6404: This name does not have a type, and must have an explicit type.   [RANK]
        if (dtype%ndims /= rank(field)) cycle
---------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(74): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%sizes(rank(field)))
-------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(75): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%subsizes(rank(field)))
----------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(76): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%starts(rank(field)))
--------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(45): error #6404: This name does not have a type, and must have an explicit type.   [RANK]
        if (dtype%ndims /= rank(field)) cycle
---------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(74): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%sizes(rank(field)))
-------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(75): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%subsizes(rank(field)))
----------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(76): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%starts(rank(field)))
--------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(45): error #6404: This name does not have a type, and must have an explicit type.   [RANK]
        if (dtype%ndims /= rank(field)) cycle
---------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(74): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%sizes(rank(field)))
-------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(75): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%subsizes(rank(field)))
----------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(76): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%starts(rank(field)))
--------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(45): error #6404: This name does not have a type, and must have an explicit type.   [RANK]
        if (dtype%ndims /= rank(field)) cycle
---------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(74): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%sizes(rank(field)))
-------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(75): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%subsizes(rank(field)))
----------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(76): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%starts(rank(field)))
--------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(45): error #6404: This name does not have a type, and must have an explicit type.   [RANK]
        if (dtype%ndims /= rank(field)) cycle
---------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(74): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%sizes(rank(field)))
-------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(75): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%subsizes(rank(field)))
----------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(76): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%starts(rank(field)))
--------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(45): error #6404: This name does not have a type, and must have an explicit type.   [RANK]
        if (dtype%ndims /= rank(field)) cycle
---------------------------^
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h(74): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [RANK]
    allocate(dtype%sizes(rank(field)))
-------------------------^
/tmp/ifortfgxoTa.i90(15024): catastrophic error: Too many errors, exiting
compilation aborted for /disk01/liuy/models/AM4/src/FMS/mpp/mpp.F90 (code 1)
make[1]: *** [mpp.o] Error 1
make[1]: Leaving directory `/disk01/liuy/models/AM4/exec/fms'
make: *** [fms/libfms.a] Error 2

Therefore, I defined the rank at the beginning as "integer :: rank" , the compiling process passed but ended with the error as follows:
fms/libfms.a(mpp.o): In function mpp_type_create_int4':
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h:46: undefined reference to rank_' /disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h:60: undefined reference to rank_'
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h:75: undefined reference to rank_' /disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h:76: undefined reference to rank_'
/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h:77: undefined reference to rank_' fms/libfms.a(mpp.o):/disk01/liuy/models/AM4/src/FMS/mpp/include/mpp_type_mpi.h:81: more undefined references to rank_' follow
ld: am4_xanadu_2021.02.x: hidden symbol `__intel_cpu_features_init_x' in /opt/intel/composer_xe_2015.1.133/compiler/lib/intel64/libirc.a(cpu_feature_disp.o) is referenced by DSO
ld: final link failed: Nonrepresentable section on output
make: *** [am4_xanadu_2021.02.x] Error 1

It seems that I did not provide a correct definition on the rank.

**Comment by thomas-robinson** [comment]
I'm not able to reproduce this issue.  Are you using intel oneapi compilers?  What version compiler are you using?  It could be a compiler issue or something like that.  This code is tested with intel 18 and intel 21

**Comment by ynueriap** [comment]
> I'm not able to reproduce this issue. Are you using intel oneapi compilers? What version compiler are you using? It could be a compiler issue or something like that. This code is tested with intel 18 and intel 21
@thomas-robinson 
The code is tested with intel 15, with which the AM2.1 and AM3 have been successfully built.  I find that the mpp module in AM4  is different from that in both the AM2.1 and AM3. I am wondering could I used the replace the fms mpp submodule to that used in AM3?
Also I will try to tested the code with intel 18. 
Thank you so much for your reply.

**Comment by thomas-robinson** [comment]
@ynueriap You might consider trying an earlier tag.  There is a `xanadu` tag that might work or there is a `v1.0.0` tag as well.  FMS has gone through some major updates over the past 6 years, and the intel 2015 compiler may not be current enough to handle it.

**Comment by ynueriap** [comment]
> @ynueriap You might consider trying an earlier tag. There is a `xanadu` tag that might work or there is a `v1.0.0` tag as well. FMS has gone through some major updates over the past 6 years, and the intel 2015 compiler may not be current enough to handle it.

@thomas-robinson You are right. It is the intel compiler issue. The code has been successfully compiled with intel 2016.
Thank you so much for your help.
