### ISSUE TITLE
An error occurred when do_concurrent_radiation=.true.

### ISSUE THREAD

**Issue by ZHONGLEI-sketch** [NOAA-GFDL/AM4#54]
&coupler_nml
        months = 6,
        days   = 0,
        current_date = 2015,9,1,0,0,0,
        calendar = 'julian'
        dt_atmos = 1800,
        dt_cpld  = 7200,
        use_lag_fluxes = .true.
        concurrent = .false.
        do_ocean = .false.
        ocean_npes = 0
        atmos_npes = 24
        atmos_nthreads = 1
        radiation_nthreads=1
        do_concurrent_radiation=.true.
        use_hyper_thread = .false.

NOTE from PE     0: radiation_driver_mod:: concurrent radiation restart active

FATAL from PE     0: The domain associated with the file: does not have an io_domain.

**Comment by thomas-robinson** [comment]
@ZHONGLEI-sketch this configuration was developed for AM3 and is untested in AM4.  Because it wasn't used in AM4 and remains untested, it is not supported here.  If you fix it, you can push the fix up to the FMScoupler repository, and we can evaluate it to see if we will consider pulling it in.
